jobs: 
    include:
        - stage: app-build-n-deploy
        if: env(GH_TOKEN) IS present
        os: osx
        osx_image: xcode10.2
        language: node_js
        node_js: "12"
        script:
            - npm test
        after_success:
            - npm run dist
